import Head from "next/head";
import Comments from "./api/comments";

export default function Services() {
  return (
    <>
      <Head>
        <title>George Sommerfield | Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
